
export const AUTH_PATHS = {
  GET_UDHYAM_DEVIATED_CASES: '/get-udhyam-deviatedCases',
  GET_SECTOR_SUBSECTOR: '/get-sector-subsector',
  GET_ALL_RECORDS: '/get-all-records',
  GET_CREDIT_APPROVED_RECORDS: '/get-credit-approved-records',
  GET_DISBURSED_RECORDS: '/get-disbursed-records',
  GET_EMPLOYEE: '/getemployee',
  GET_REJECTED_PRE_CASE: '/get-rejected-pre-case',
  GET_MSME_CUSTOMER_DETAILS: '/get-msme-customer-details',
  GET_MSME_LEAD: '/get-msme-lead',
  GET_MSME_STATIC_DETAILS: '/get-msme-static-details',
  GET_GOOGLE_BRE: '/get-google-bre',
  GET_MSME_BRE_DETAILS: '/get-msme-bre-details',
  GET_COMPREHENSIVE_CREDIT_REPORT: '/GetComprehensiveCreditReport',
  UPDATE_DEVIATED_CASE: '/updateDeviatedCase',
  UPDATE_UDYAM_DOCS: '/updateUdyamDocs',
  REJECT_DEVIATED_CASE: '/rejectDeviatedCase',
  LANDMARK_BY_AGENT: '/landmarkByAgent',
  SAVE_CPV: '/saveCpv',
  PENDING_DEVIATED_CASE: '/pendingDeviatedCase',
  UPDATE_SECTOR_SUBSECTOR_CASE: '/updateSectorSubsectorCase',
  UPDATE_EMPLOYEE_STATUS: '/updateEmployeeStatus',
  INSERT_MSME_COMMENT: '/insertMsmeComment',
  INSERT_EMPLOYEE: '/insertEmployee',
  GET_SUMMARY: '/getSummary',
  GET_EMPLOYEE_ROLE: '/getEmployeeRole',
  GET_EMPLOYEE_DETAIL: '/getEmployeeDetail',
  GET_COMMENT: '/getComment/:id',
  GET_CASE_DOCS: '/getCaseDocs',
  WEB_UPLOAD_BUSINESS_IMAGE: '/webUploadBusinessImage',
  WEB_GET_BUSINESS_IMAGE: '/webGetBusinessImage',
  GET_MSME_LEAD_IMAGE: '/getMsmeLeadImage/:id',
  GET_USER_JOURNEY_DETAILS: '/get-user-journey/:id',
  BUSINESS_LEAD_GENERATION: '/business-lead-generation',
  LEAD_REMARK_OPTIONS: '/lead-remark-options',
  AGGREGATOR_BANK_STATEMENT: '/aggregatorbankStatment',
  AGGREGATOR_BANK_STATEMENT_EXCEL: '/aggregatorbankStatmentexcel',
  USER_JOURNEY: '/userJourney',
  GET_AO_DETAILS: '/getAoDetails',
  MSME_REPORT: '/msme/report',
  GET_AO_IMAGE: '/get_ao_image',
  GET_AGENT_ACTION: '/getAgentAction',
  GET_ACTIVE_AGENT: '/getActiveAgent'

};
